stages:
    - build

build:
    stage: build
    script:
        - "dotnet restore"
        - "msbuild.exe dExcel/dExcel.csproj --configuration Release"
        - "mkdir publish"
        - "cp dExcel/bin/Release/net6.0-windows/*.* publish"
    artifacts:
        paths:
        - publish/*.*
        expire_in: 1 day
    tags:
        - windows
