#image: mcr.microsoft.com/dotnet/sdk:latest
image: mcr.microsoft.com/windows/servercore:ltsc2022

stages:
    - build

build:
    stage: build
    script:
        - "dotnet restore"
        - "dotnet build --configuration Release"
        - "mkdir publish"
        - "cp dExcel/bin/Release/net6.0-windows/*.* publish"
    artifacts:
        paths:
        - publish/*.*
        expire_in: 1 day
