#- ""
stages:
    - build
    - test

build:
    stage: build
    script:
        - pwd
        - "& 'C:\\Nuget\\nuget.exe' restore dExcel.sln -OutputDirectory C:\\GitLab-Runner\\packages"
        - "& 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\msbuild.exe' -t:restore,build dExcel.sln -p:RestorePackagesPath='C:\\gitlab-runner\\packages' -p:RestorePackagesConfig=true /property:Configuration=Release"
        - "mkdir publish"
        - "cp dExcel/bin/Release/net6.0-windows/*.* publish"
    artifacts:
        paths:
        - publish/*.*
        expire_in: 1 day
    tags:
        - windows

test:
    stage: test
    script:
        - pwd
        - "mkdir CoverageResults" 
        - "& 'C:\\GitLab-Runner\\packages\\opencover\\4.7.1221\\tools\\OpenCover.Console.exe' -target:'C:\\GitLab-Runner\\packages\\nunit.consolerunner\\3.16.0\\tools\\nunit3-console.exe' -targetargs:'dExcelTests\\bin\\Release\\net6.0-windows\\dExcelTests.dll' -targetdir:'CoverageResults' -output:'CoverageResults\\results.xmsl'"
    tags:
        - windows
